### ISSUE TITLE
Remove mongodb as requirement

### ISSUE THREAD

**Issue by sacdallago** [gyachdav/awoiaf#16]
I saw that there's code to interact with mongo via pymongo, but it's all commented out. Out of clarity wouldn't it be wise to branch the current version to something like "mongo implementation" and get rid of all references to mongo on the main branch?

**Comment by gyachdav** [comment]
Started a new branch mongodb and removed all references to mongo related code from master branch

**Comment by sacdallago** [comment]
Nice :+1:
