### ISSUE TITLE
Vague instructions

### ISSUE THREAD

**Issue by sacdallago** [gyachdav/awoiaf#7]
```
Look at the scripts in the scr folder to see how the modules in this app can be used and to build your data repository.
```

is not really telling me much :D I tried reading the scripts but I'm no python expert and some things I understand, other things I don't... And being unable to run the scripts (see issue #5 #6  ) I cannot really test out any further

**Comment by gyachdav** [comment]
expanded documentation in README and in #a7a778b8ed60c2683b9957d0d432a80865fbfc2e

**Comment by gyachdav** [comment]
Christian please let me know if we can close this issue

**Comment by sacdallago** [comment]
Sorry Guy it has been a busy weekend and I still haven't been in front of a
PC since past Thursday. Tomorrow I will be travelling back to Munich and
look at the changes and open issues and report back

## 

Christian Dallago

U.S.: +1 (843) 410-9775
Italy: +39 0471 17 26 333
Germany: +49 89 721010 89550
International: http://dallago.mtalk.net/

http://dallago.us

Sent from my mobile device - sorry for brevity &/| typos
